@startuml

title __CONFIG's Class Diagram__\n

  namespace apiservice.car {
    namespace config {
      class apiservice.car.config.FirebaseConfig {
          + getAuth()
          + getDB()
          + getFirebaseApp()
      }
    }
  }
  

  namespace apiservice.car {
    namespace config {
      class apiservice.car.config.JacksonConfig {
          + jacksonObjectMapper()
      }
    }
  }
  

  apiservice.car.config.FirebaseConfig o-- apiservice.car.security.models.SecurityProperties : secProps


right footer

endfooter

@enduml
