spring:
  config:
    activate:
      on-profile: "dev"
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672

logging:
  level:
    org: ERROR

---

spring:
  config:
    activate:
      on-profile: "docker"
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
    port: 5672

logging:
  level:
    org: ERROR