spring:
  profiles:
    active: "dev"
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672

logging:
  level:
    org: ERROR

---

spring:
  profiles:
    active: "docker"
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
    port: 5672

logging:
  level:
    org: ERROR