@startuml

title __HANDLER's Class Diagram__\n

  namespace orchestrator {
    namespace handler {
      interface orchestrator.handler.EndpointHandler {
          {abstract} + handle()
      }
    }
  }
  

  namespace orchestrator {
    namespace handler {
      abstract class orchestrator.handler.HandlerRequest {
          - userId : String
          + HandlerRequest()
          + equals()
          + getUserId()
          + hashCode()
          + setUserId()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace orchestrator {
    namespace handler {
      abstract class orchestrator.handler.HandlerResponse {
          - userId : String
          + HandlerResponse()
          + equals()
          + getUserId()
          + hashCode()
          + setUserId()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace orchestrator {
    namespace handler {
      class orchestrator.handler.RabbitMQDirectConfig {
          {static} + CALENDAR_KEY : String
          {static} + CALENDAR_QUEUE : String
          {static} + EMAIL_KEY : String
          {static} + EMAIL_QUEUE : String
          {static} + EXCHANGE : String
          {static} + LEGAL_KEY : String
          {static} + LEGAL_QUEUE : String
          {static} + ORCHESTRATOR_KEY : String
          {static} + ORCHESTRATOR_QUEUE : String
          - amqpAdmin : AmqpAdmin
          + createQueues()
          ~ calendarBinding()
          ~ calendarQueue()
          ~ emailBinding()
          ~ emailQueue()
          ~ exchange()
          ~ legalBinding()
          ~ legalQueue()
          ~ orchestratorBinding()
          ~ orchestratorQueue()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
