version: '3'

services:
  business-handler:
    container_name: business-handler
    image: "docker.pkg.github.com/marcllort/canitravelto_backend/business-handler:${BUSINESS_VERSION}"
    command: "/dist/main /build/Creds ${DB_PASSWORD}"
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      backend-network:
        ipv4_address: 10.5.0.5

  data-retriever:
    container_name: data-retriever
    image: "docker.pkg.github.com/marcllort/canitravelto_backend/data-retriever:${DATA_VERSION}"
    command: "/dist/main /build/Creds ${DB_PASSWORD}"
    restart: unless-stopped


networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16