apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-deployment
  labels:
    app: calendar-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-middleware
  template:
    metadata:
      labels:
        app: calendar-middleware
    spec:
      containers:
        - name: calendar-pod
          image: marcllort/car-rental-calendar:latest
          ports:
            - containerPort: 8080
          env:
            - name: URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: SECRET_DB
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: SECRET_DB
            - name: CREDS
              value: /database/creds.json
            - name: CREDS_CALENDAR
              value: /calendar/calendar-api-credentials.json
            - name: CREDS_FIRESTORE
              value: /firestore/car-rental.json
          volumeMounts:
            - name: database-config-volume
              mountPath: /database/
              readOnly: true # no editing!
            - name: calendar-config-volume
              mountPath: /calendar/
              readOnly: true # no editing!
            - name: firebase-config-volume
              mountPath: /firestore/
              readOnly: true # no editing!
      volumes:
        - name: database-config-volume
          secret:
            secretName: dbcreds-secret
        - name: calendar-config-volume
          secret:
            secretName: calendar-secret
        - name: firebase-config-volume
          secret:
            secretName: firebase-secret
