apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-deployment
  labels:
    app: calendar-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-middleware
  template:
    metadata:
      labels:
        app: calendar-middleware
    spec:
      containers:
        - name: legal-middleware
          image: marcllort/car-rental-calendar:latest
          ports:
            - containerPort: 8080
          env:
            - name: URL
              value: "amqp://guest:guest@rabbitmq:5672"
