@startuml

title __MODEL's Class Diagram__\n

  namespace apiservice.car {
    namespace model {
      class apiservice.car.model.FirebaseUserRequest {
          - calendarURL : String
          - checked : boolean
          - city : String
          - code : String
          - country : String
          - email : String
          - emailSign : String
          - language : String
          - name : String
          - password : String
          - phone : String
          - uid : String
          + FirebaseUserRequest()
          + equals()
          + getCalendarURL()
          + getCity()
          + getCode()
          + getCountry()
          + getEmail()
          + getEmailSign()
          + getLanguage()
          + getName()
          + getPassword()
          + getPhone()
          + getUid()
          + hashCode()
          + isChecked()
          + setCalendarURL()
          + setChecked()
          + setCity()
          + setCode()
          + setCountry()
          + setEmail()
          + setEmailSign()
          + setLanguage()
          + setName()
          + setPassword()
          + setPhone()
          + setUid()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace apiservice.car {
    namespace model {
      class apiservice.car.model.Service {
          - BasePrice : Float
          - CalendarEvent : String
          - ClientId : int
          - ConfirmedDatetime : ZonedDateTime
          - Description : String
          - Destination : String
          - DriverId : int
          - ExtraPrice : Float
          - Origin : String
          - Passengers : int
          - PayedDatetime : ZonedDateTime
          - ServiceDatetime : ZonedDateTime
          - ServiceId : int
          - SpecialNeeds : String
          + Service()
          + equals()
          + getBasePrice()
          + getCalendarEvent()
          + getClientId()
          + getConfirmedDatetime()
          + getDescription()
          + getDestination()
          + getDriverId()
          + getExtraPrice()
          + getOrigin()
          + getPassengers()
          + getPayedDatetime()
          + getServiceDatetime()
          + getServiceId()
          + getSpecialNeeds()
          + hashCode()
          + setBasePrice()
          + setCalendarEvent()
          + setClientId()
          + setConfirmedDatetime()
          + setDescription()
          + setDestination()
          + setDriverId()
          + setExtraPrice()
          + setOrigin()
          + setPassengers()
          + setPayedDatetime()
          + setServiceDatetime()
          + setServiceId()
          + setSpecialNeeds()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace apiservice.car {
    namespace model {
      class apiservice.car.model.UserRequest {
          - customClaim : String
          - disabled : String
          - displayName : String
          - email : String
          - emailVerified : String
          - password : String
          - phoneNumber : String
          - photoURL : String
          + UserRequest()
          + equals()
          + getCustomClaim()
          + getDisabled()
          + getDisplayName()
          + getEmail()
          + getEmailVerified()
          + getPassword()
          + getPhoneNumber()
          + getPhotoURL()
          + hashCode()
          + setCustomClaim()
          + setDisabled()
          + setDisplayName()
          + setEmail()
          + setEmailVerified()
          + setPassword()
          + setPhoneNumber()
          + setPhotoURL()
          + toString()
          # canEqual()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
